models/user.py
from extentions import db
from datetime import datetime


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    phone = db.Column(db.String(50))
    email = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(50))
    date_joined = db.Column(db.Date, default=datetime.utcnow)
    shopping_cart = db.Column(db.String())

    def __init__(self, first_name, last_name, phone, email, password):
        self.first_name = first_name
        self.last_name = last_name
        self.phone = phone
        self.email = email
        self.password = password

main.py
from flask import Flask, redirect, url_for, render_template, session, flash

from settings import SECRET_KEY, PERMANENT_SESSION_LIFETIME, SQLALCHEMY_DATABASE_URI, SQLALCHEMY_TRACK_MODIFICATIONS

from extentions import db, shopping_cart

from views.authenticate import authenticate
from views.manipulate import manipulate
from views.view import view

app = Flask(__name__)

app.secret_key = SECRET_KEY
app.permanent_session_lifetime = PERMANENT_SESSION_LIFETIME

app.config["SQLALCHEMY_DATABASE_URI"] = SQLALCHEMY_DATABASE_URI
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = SQLALCHEMY_TRACK_MODIFICATIONS

db.init_app(app)

app.register_blueprint(authenticate)
app.register_blueprint(manipulate)
app.register_blueprint(view)


@app.route("/")
def home():
    return render_template("home.html")


@app.route("/menu")
def menu():
    if "email" in session:
        email = session["email"]
        products_num = shopping_cart.get_products_num()
        return render_template("menu.html", user=email, products_num=products_num)
    else:
        flash("You are not logged in!")
        return redirect(url_for("login"))


if __name__ == "__main__":
    with app.app_context():
        db.create_all()
    # app.run(host="0.0.0.0")
    app.run()

views/authenticate.py
from flask import Blueprint, redirect, url_for, render_template, request, session, flash
import json
from extentions import db, shopping_cart
from models.user import User

authenticate = Blueprint("authenticate", __name__)


@authenticate.route("/signin", methods=["GET", "POST"])
def signin():
    if request.method == "POST":
        session.permanent = True
        first_name = request.form["first_name"]
        last_name = request.form["last_name"]
        phone = request.form["phone"]
        email = request.form["email"]
        password = request.form["password"]
        session["email"] = email
        session["password"] = password

        found_user = User.query.filter_by(email=email).first()
        if found_user:
            flash("This email is already in use by an existing user, "
                  "please signin using a unique email / login using some other user in order to continue")
            return redirect(url_for("home"))
        else:
            user = User(first_name=first_name, last_name=last_name, phone=phone, email=email, password=password)
            db.session.add(user)
            db.session.commit()
            flash("Signed in successfully!")
            return redirect(url_for("menu"))
    else:
        return render_template("signin.html")


@authenticate.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        session.permanent = True
        email = request.form["email"]
        password = request.form["password"]
        session["email"] = email
        session["password"] = password

        found_user = User.query.filter_by(email=email).first()
        if found_user:
            if password == found_user.password:
                shopping_cart.shopping_dict = json.loads(found_user.shopping_cart) if found_user.shopping_cart else {}
            else:
                flash("Password is incorrect! please try again.")
                return render_template("login.html")
        else:
            flash("User is not registered, please signin / login using some other user in order to continue.")
            return redirect(url_for("home"))

        flash("Logged in successfully!")
        return redirect(url_for("menu"))
    else:
        if "email" in session:
            flash("Already logged in.")
            return redirect(url_for("menu"))
        return render_template("login.html")


@authenticate.route("/logout")
def logout():
    if "email" in session:
        email = session.pop("email")
        session.pop("password")
        flash(f"{email} have been logged out!")
    return redirect(url_for("authenticate.login"))


@authenticate.route("/edit")
def edit_profile():
    pass

views/manipulate.py
from flask import Blueprint, redirect, url_for, render_template, request, session, flash
import json
from extentions import db, shopping_cart
from models.user import User

manipulate = Blueprint("manipulate", __name__)


@manipulate.route("/add", methods=["GET", "POST"])
def add_product():
    if "email" in session:
        if request.method == "POST":
            product_name = request.form.get("product_name")
            quantity = request.form.get("quantity")
            added = shopping_cart.add_product(product_name, int(quantity))
            if added:
                email = session["email"]
                found_user = User.query.filter_by(email=email).first()
                found_user.shopping_cart = json.dumps(shopping_cart.shopping_dict)
                db.session.commit()
                flash(f"{product_name} X {quantity} added to the shopping cart.")
                return redirect(url_for("menu"))
            else:
                flash("Product already appears in the shopping cart, you can update its quantity if necessary.")
                return redirect(url_for("update_product"))
        else:
            return render_template("add.html")
    else:
        flash("You are not logged in!")
        return redirect(url_for("authenticate.login"))


@manipulate.route("/update", methods=["GET", "POST"])
def update_product():
    if "email" in session:
        if request.method == "POST":
            product_name = request.form.get("product_name")
            quantity = request.form.get("quantity")
            total = shopping_cart.update_product(product_name, int(quantity))
            if total:
                email = session["email"]
                found_user = User.query.filter_by(email=email).first()
                found_user.shopping_cart = json.dumps(shopping_cart.shopping_dict)
                db.session.commit()
                flash(f"{product_name} X {total} in the shopping cart.")
                return redirect(url_for("menu"))
            else:
                flash("Product does not appear in the shopping cart, please add it first.")
                return redirect(url_for("add_product"))
        else:
            return render_template("update.html")
    else:
        flash("You are not logged in!")
        return redirect(url_for("authenticate.login"))


@manipulate.route("/remove", methods=["GET", "POST"])
def remove_product():
    if "email" in session:
        if request.method == "POST":
            product_name = request.form.get("product_name")
            quantity = request.form.get("quantity")
            removed = shopping_cart.remove_product(product_name, int(quantity))
            if removed:
                email = session["email"]
                found_user = User.query.filter_by(email=email).first()
                found_user.shopping_cart = json.dumps(shopping_cart.shopping_dict)
                db.session.commit()
                flash(f"{product_name} X {quantity} removed from the shopping cart.")
                return redirect(url_for("menu"))
            else:
                flash(f"Product {product_name} does not appear in the shopping cart!")
                return redirect(url_for("menu"))
        else:
            return render_template("remove.html")
    else:
        flash("You are not logged in!")
        return redirect(url_for("authenticate.login"))

views/view.py
from flask import Blueprint, redirect, url_for, render_template, session, flash
from extentions import shopping_cart
from models.user import User

view = Blueprint("view", __name__)


@view.route("/cart")
def view_cart():
    if "email" in session:
        col_titles_list = ["#", "Product", "Quantity"]
        row_vals_lists = [[product, quantity] for product, quantity in shopping_cart.shopping_dict.items()]
        return render_template("cart.html", col_titles_list=col_titles_list,
                               row_vals_lists=row_vals_lists)
    else:
        flash("You are not logged in!")
        return redirect(url_for("authenticate.login"))


@view.route("/users")
def view_users():
    return render_template("users.html", users=User.query.all())

templates/add.html
{% extends "manipulate.html" %}
{% block title %}Add Product{% endblock %}
{% block head %}Add Product{% endblock %}

templates/base.html
<html>
    <head>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/style.css')}}">
        <title>
            {% block title %}{% endblock %}
        </title>
    </head>
    <body>
        <div class="container-fluid">
        {% block content %}{% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/cart.html
{% extends "base.html" %}
{% block title %}Shopping Cart{% endblock %}
{% block content %}
{% include "table.html" %}
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}Shopping Assistant{% endblock %}
{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
    {% endif %}
{% endwith %}
<h1>Hello, I am your shopping assistant :)</h1>

<image src="{{ url_for('static', filename='images/shoppingcart.png') }}"></image>

<h2>If it's the first time you're using the shopping assistant, please press "signin" in order to continue:</h2>
<a href="{{ url_for('authenticate.signin') }}">Signin</a>

<h2>Already registered as a user? please press "login" in order to continue:</h2>
<a href="{{ url_for('authenticate.login') }}">Login</a>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login Page{% endblock %}
{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
    {% endif %}
{% endwith %}
<h1>Login</h1>
<form action="#" method="post">
    <p>Email:</p>
    <input type="email" name="email" placeholder="Enter Your Email" required>
    <p>Password:</p>
    <input type="Password" name="password" placeholder="Enter Your Password" required>
    <input type="submit" name="submit"/>
</form>
{% endblock %}

templates/manipulate.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
    {% endif %}
{% endwith %}
<h1>{% block head %}{% endblock %}</h1>
<form action="#" method="post">
    <p>Product Name:</p>
    <input type="text" name="product_name" required>
    <p>Quantity:</p>
    <input type="text" name="quantity" value="1">
    <input type="submit" name="submit"/>
</form>
{% endblock %}

templates/menu.html
{% extends "base.html" %}
{% block title %}Shopping Assistant{% endblock %}
{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
    {% endif %}
{% endwith %}
<h1>Hello {{user}}!</h1>
{% if products_num is not none %}
<h2>Currently you have {{products_num}} products in the shopping cart.</h2>
{% endif %}
<h3>Please select the desired action:</h3>
<ul class="menu">
    <li><a href="{{ url_for('manipulate.add_product') }}">Add Product</a></li>
    <li><a href="{{ url_for('manipulate.update_product') }}">Update Product</a></li>
    <li><a href="{{ url_for('manipulate.remove_product') }}">Remove Product</a></li>
    <li><a href="{{ url_for('view.view_cart') }}">View Shopping Cart</a></li>
</ul>
{% endblock %}

<form action="#" method="post">
    <p>Email:</p>
    <input type="email" name="email" placeholder="Enter your email" value="{{email if email}}">
    <input type="submit" name="submit"/>
</form>

templates/present_shopping_list.html
{% extends "base.html" %}
{% block title %}Shopping List{% endblock %}
{% block content %}
{% include "table.html" %}
{% endblock %}

templates/remove.html
{% extends "manipulate.html" %}
{% block title %}Remove Product{% endblock %}
{% block head %}Remove Product{% endblock %}

templates/signin.html
{% extends "base.html" %}
{% block title %}Login Page{% endblock %}
{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
    {% endif %}
{% endwith %}
<h1>Login</h1>
<form action="#" method="post">
    <p>First Name:</p>
    <input type="text" name="first_name" placeholder="Enter Your First Name" required>
    <p>Last Name:</p>
    <input type="text" name="last_name" placeholder="Enter Your Last Name" required>
    <p>Phone Number:</p>
    <input type="tel" name="phone" placeholder="Enter Your Phone Number" required>
    <p>Email:</p>
    <input type="email" name="email" placeholder="Enter Your Email" required>
    <p>Password:</p>
    <input type="password" name="password" placeholder="Enter Your password" required>
    <input type="submit" name="submit"/>
</form>
{% endblock %}

templates/table.html
<table class="table table-striped">
  <thead>
    <tr>
      {% for col_title in col_titles_list %}
      <th scope="col">{{col_title}}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
      {% for row_vals_list in row_vals_lists %}
        <tr>
          <th scope="row">{{loop.index}}</th>
          {% for row_val in row_vals_list %}
            <td>{{row_val}}</td>
          {% endfor %}
        </tr>
      {% endfor %}
  </tbody>
</table>

templates/update.html
{% extends "manipulate.html" %}
{% block title %}Update Product{% endblock %}
{% block head %}Update Product{% endblock %}

templates/users.html
{% extends "base.html" %}
{% block title %}View All Users{% endblock %}
{% block content %}
    {% for user in users %}
        <p>Name: {{user.email}}, Date Joined: {{user.date_joined}}</p>
    {% endfor %}
{% endblock %}

templates/view.html
{% extends "base.html" %}
{% block title %}View All Users{% endblock %}
{% block content %}
    {% for user in users %}
        <p>Name: {{user.email}}, Date Joined: {{user.date_joined}}</p>
    {% endfor %}
{% endblock %}